services:
  - type: web
    name: smartbiz-rag
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1
    envVars:
      - key: MONGO_URI
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: UPLOAD_FOLDER
        value: /tmp/data
      - key: CHROMA_DB_PATH
        value: /tmp/chroma_db
      - key: ANONYMIZED_TELEMETRY
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
